<a href="https://colab.research.google.com/github/hasanfaesal/pytorch-tutorials/blob/main/02tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

December 10th 2024, Tuesday
PyTorch Tutorial 02 - Tensors

20:24

Tensors are specialized multi-dimensional arrays used for mathematical & computational efficiency.
examples include:
-> scalars
-> vectors
-> matrices
-> n-dimensional arrays

Q. Why are Tensors Useful?
1. mathematical operations
2. representation of real-world data (images,audio,videos,text)
3. efficient computation

Q. Where are Tensors Used in Deep Learning?
1. Data Storage
2. Weights and Biases
3. Matrix Operations
4. Training Process (forwardpass and backwardpass)


In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available, Using CPU")

GPU is available
Using GPU: Tesla T4


## Creating a Tensor

In [5]:
a = torch.empty(2,3)

In [6]:
type(a)

torch.Tensor

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.rand(2,3)

tensor([[0.8168, 0.1845, 0.2030],
        [0.0496, 0.2140, 0.1142]])

In [10]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [11]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [12]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])