<a href="https://colab.research.google.com/github/hasanfaesal/pytorch-tutorials/blob/main/04training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Training pipeline for building Neural Networks (manually)
this notebook focuses on the manual aspects of defining the neural net architecture and then training it via a loop.

later notebooks intend to shift the focus from manual to auto facilitation by PyTorch's module and functions.

In [1]:
import pandas as pd
import numpy as np
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['Unnamed: 32', 'id'], inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## train test split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.25, random_state=42)

## scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.34913849, -1.43851335, -0.41172595, ..., -0.91671059,
        -0.92508585, -0.80841115],
       [-0.20468665,  0.31264011, -0.13367256, ...,  1.43655962,
         1.14955889,  1.56911143],
       [-0.32931176, -0.21507235, -0.31739376, ..., -0.7237126 ,
         0.53496977, -0.61934827],
       ...,
       [ 0.04739597, -0.56293662, -0.06529202, ..., -1.23262438,
        -0.68282718, -1.261137  ],
       [-0.04040808,  0.09966199, -0.03151368, ...,  1.08847951,
         0.48944465,  1.26159953],
       [-0.5502381 ,  0.31264011, -0.6040977 , ..., -0.59582424,
        -0.29911546, -0.82948141]])

## label encoding
it is a binary classification problem, converting categorical labels to numerical

In [9]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
y_train

array([0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,

## converting NumPy arrays to PyTorch tensors

In [11]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [12]:
print(X_train_tensor.shape)
print(X_train_tensor.dtype)

torch.Size([426, 30])
torch.float64


In [13]:
print(X_test_tensor.shape)
print(X_test_tensor.dtype)

torch.Size([143, 30])
torch.float64


## defining the model

In [14]:
class NeuralNetwork():

  def __init__(self, X):

#initializing weights from random
    self.weights = torch.rand(X.shape[1],1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
      # z = wx + b
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)

    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # calculate loss
    loss = -y * torch.log(y_pred) - (1-y) * torch.log(1-y_pred)
    loss = torch.mean(loss)

    return loss

## important parameters

In [15]:
learning_rate = 0.1
epochs = 50

## training pipeline

In [16]:
# create model
model = NeuralNetwork(X_train_tensor)

# define loop for epochs
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # calculate loss
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # update parameters
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients - to avoid gradient accumulation
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}')

Epoch 1/50, Loss: 3.3192
Epoch 2/50, Loss: 3.1770
Epoch 3/50, Loss: 3.0327
Epoch 4/50, Loss: 2.8819
Epoch 5/50, Loss: 2.7296
Epoch 6/50, Loss: 2.5783
Epoch 7/50, Loss: 2.4250
Epoch 8/50, Loss: 2.2694
Epoch 9/50, Loss: 2.1135
Epoch 10/50, Loss: 1.9579
Epoch 11/50, Loss: 1.8050
Epoch 12/50, Loss: 1.6615
Epoch 13/50, Loss: 1.5287
Epoch 14/50, Loss: 1.4040
Epoch 15/50, Loss: 1.2931
Epoch 16/50, Loss: 1.1948
Epoch 17/50, Loss: 1.1122
Epoch 18/50, Loss: 1.0445
Epoch 19/50, Loss: 0.9899
Epoch 20/50, Loss: 0.9459
Epoch 21/50, Loss: 0.9107
Epoch 22/50, Loss: 0.8822
Epoch 23/50, Loss: 0.8589
Epoch 24/50, Loss: 0.8397
Epoch 25/50, Loss: 0.8235
Epoch 26/50, Loss: 0.8097
Epoch 27/50, Loss: 0.7978
Epoch 28/50, Loss: 0.7875
Epoch 29/50, Loss: 0.7784
Epoch 30/50, Loss: 0.7704
Epoch 31/50, Loss: 0.7633
Epoch 32/50, Loss: 0.7570
Epoch 33/50, Loss: 0.7513
Epoch 34/50, Loss: 0.7462
Epoch 35/50, Loss: 0.7415
Epoch 36/50, Loss: 0.7374
Epoch 37/50, Loss: 0.7335
Epoch 38/50, Loss: 0.7301
Epoch 39/50, Loss: 0.

In [17]:
model.weights

tensor([[ 0.1348],
        [-0.3870],
        [-0.2311],
        [-0.0852],
        [-0.2230],
        [ 0.2515],
        [-0.3041],
        [ 0.0933],
        [ 0.1617],
        [-0.0738],
        [-0.2921],
        [ 0.3389],
        [-0.3362],
        [ 0.4091],
        [ 0.4431],
        [-0.1490],
        [ 0.2386],
        [ 0.1623],
        [-0.2148],
        [-0.2395],
        [ 0.1285],
        [ 0.2957],
        [ 0.0385],
        [-0.1814],
        [-0.1153],
        [-0.2332],
        [ 0.3405],
        [ 0.3291],
        [ 0.0373],
        [-0.2099]], dtype=torch.float64, requires_grad=True)

In [18]:
model.bias

tensor([-0.3365], dtype=torch.float64, requires_grad=True)

## Model Evaluation

In [19]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item():.4f}')

Accuracy: 0.5642
