In [1]:
import torch
import torch.nn as nn

In [7]:
# create the model class
class NeuralNet(nn.Module):

  def __init__(self, input_size):

    super().__init__()

    self.network = nn.Sequential(
    nn.Linear(input_size, 3), # (batch_size, num_features)
    nn.ReLU(),

    nn.Linear(3, 1), # could name as linear2
    nn.Sigmoid()
    )

  def forward(self, input): # use sequential container for the forward pass
    output = self.network(input)

    return output

In [8]:
# create dummy dataset
features = torch.rand(10,5)

# create model
model = NeuralNet(features.shape[1])

# call model for forward pass
# instead of mode.forward(features)
model(features)

tensor([[0.4897],
        [0.4768],
        [0.4867],
        [0.4763],
        [0.4861],
        [0.4841],
        [0.4772],
        [0.4819],
        [0.4848],
        [0.4806]], grad_fn=<SigmoidBackward0>)

In [11]:
# Display weights and biases
for name, param in model.named_parameters():
    if param.requires_grad:
        print(f"Layer: {name}")
        print(f"Values:\n{param.data}\n")

# Get weights and biases of the first Linear layer
print("First Layer Weights:\n", model.network[0].weight.data)
print("First Layer Bias:\n", model.network[0].bias.data)

# Get weights and biases of the second Linear layer
print("Second Layer Weights:\n", model.network[2].weight.data)
print("Second Layer Bias:\n", model.network[2].bias.data)

Layer: network.0.weight
Values:
tensor([[-0.1070, -0.4227,  0.2511, -0.1721,  0.3413],
        [-0.1619, -0.0191, -0.2445,  0.0786,  0.4072],
        [ 0.3460,  0.3942,  0.3690, -0.3110,  0.3494]])

Layer: network.0.bias
Values:
tensor([ 0.3666, -0.0595, -0.3575])

Layer: network.2.weight
Values:
tensor([[ 0.1142, -0.2105,  0.0397]])

Layer: network.2.bias
Values:
tensor([-0.1206])

First Layer Weights:
 tensor([[-0.1070, -0.4227,  0.2511, -0.1721,  0.3413],
        [-0.1619, -0.0191, -0.2445,  0.0786,  0.4072],
        [ 0.3460,  0.3942,  0.3690, -0.3110,  0.3494]])
First Layer Bias:
 tensor([ 0.3666, -0.0595, -0.3575])
Second Layer Weights:
 tensor([[ 0.1142, -0.2105,  0.0397]])
Second Layer Bias:
 tensor([-0.1206])


In [6]:
!pip install torchinfo
from torchinfo import summary

summary(model, input_size=(10,5))

RuntimeError: Failed to run torchinfo. See above stack traces for more details. Executed layers up to: []