In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
# Creating classification dataset
X, y = make_classification(
    n_samples=100,
    n_features=5,
    n_informative=3,
    n_classes=2,
    random_state=42
)

In [4]:
X.shape

(100, 5)

In [6]:
y.shape

(100,)

In [7]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [9]:
print(X.dtype)
print(y.dtype)

torch.float32
torch.int64


## Using dataset and dataloader classes now

In [10]:
from torch.utils.data import Dataset, DataLoader

In [11]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [12]:
dataset = CustomDataset(X, y)

In [14]:
print(len(dataset))
dataset[0]

100


(tensor([-0.5166,  0.1465,  0.7529,  1.6036,  0.7435]), tensor(1))

In [15]:
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

In [16]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)

  print('-'*100)

tensor([[ 1.0161, -1.0365, -0.6581, -0.6825, -0.5673],
        [-0.0964, -0.7636,  1.6033,  1.3989, -0.5426],
        [-0.5166,  0.1465,  0.7529,  1.6036,  0.7435],
        [ 1.0075, -0.5209, -1.1014, -2.6269, -1.4658]])
tensor([0, 0, 1, 0])
----------------------------------------------------------------------------------------------------
tensor([[-1.0992e+00,  2.2038e+00, -2.4403e+00,  2.1658e+00,  4.7009e+00],
        [-2.6718e-01,  9.2133e-01, -1.7099e+00,  1.0193e+00,  2.5818e+00],
        [-2.2590e-01,  3.4715e-01, -7.5247e-02,  3.9331e-03,  2.4225e-01],
        [-1.1099e+00,  2.2010e+00, -1.3049e+00, -6.2117e-01,  1.6689e+00]])
tensor([1, 1, 1, 0])
----------------------------------------------------------------------------------------------------
tensor([[ 1.0578, -0.4715, -1.5474, -2.2207, -0.7835],
        [-0.3376, -0.8564,  1.9923,  3.0360,  0.3805],
        [-1.1811,  2.3531, -2.1546,  1.2266,  3.8320],
        [ 1.4602, -0.8857, -1.9501, -2.1066, -0.6032]])
tensor([0, 0,